/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Renderer {
  constructor(connectionStr: string, hillshadingBase: string, svgBase: string)
  render(bbox: [number, number, number, number], zoom: number, scales: Array<number>, format?: string | undefined | null): RenderResult
}

export interface RenderResult {
  contentType: string
  images: Array<Buffer>
}
