/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Renderer {
  constructor(connectionStr: string, hillshadingBase: string, svgBase: string);
  render(
    bbox: [number, number, number, number],
    zoom: number,
    scale?: number | undefined | null,
    format?: string | undefined | null
  ): RenderResult;
}

export interface RenderResult {
  data: Buffer;
  contentType: string;
}
