pub use crate::render::categories::Category;
pub use hillshading_datasets::HillshadingDatasets;
pub use hillshading_datasets::load_hillshading_datasets;
pub use landcover::PAINT_DEFS;
pub use pipeline::RenderError;
pub use pipeline::Shading;
pub use pipeline::render;
pub use pois::{Def, POI_ORDER, POIS};

mod aerialway_names;
mod blur_edges;
mod bordered_area_names;
mod borders;
mod bridge_areas;
mod building_names;
mod buildings;
mod contours;
mod country_names;
mod custom;
mod decorations;
mod embankments;
mod feature_lines;
mod fixmes;
mod geonames;
mod highway_names;
mod hillshading;
mod hillshading_datasets;
mod housenumbers;
mod landcover;
mod landcover_names;
mod landcover_z_order;
mod locality_names;
mod military_areas;
mod national_park_names;
mod pipeline;
pub mod place_names;
mod poi_z_order;
mod pois;
mod power_towers_poles;
mod protected_areas;
mod road_access_restrictions;
mod roads;
mod routes;
mod sea;
mod shading_and_contours;
mod solar_power_plants;
mod special_park_names;
mod special_parks;
mod trees;
mod valleys_ridges;
mod water_area_names;
mod water_areas;
mod water_line_names;
mod water_lines;
