/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum ImageFormat {
  Png = 'Png',
  Jpeg = 'Jpeg',
  Pdf = 'Pdf',
  Svg = 'Svg'
}
export declare class Renderer {
  constructor(connectionStr: string, hillshadingBase: string | undefined | null, svgBase: string, dbPriority?: number | undefined | null, maskGeojsonPath?: string | undefined | null)
  render(bbox: [number, number, number, number], zoom: number, scales: Array<number>, format: ImageFormat, extra?: RequestExtra | undefined | null): RenderResult
}

export interface RenderResult {
  contentType: string
  images: Array<Buffer>
}

export interface RequestExtra {
  shading?: boolean
  contours?: boolean
  hikingRoutes?: boolean
  bicycleRoutes?: boolean
  skiRoutes?: boolean
  horseRoutes?: boolean
  featureCollection?: string
}
